test = {   'name': 'q0_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(dc_clean, bpd.DataFrame) and isinstance(marvel_clean, bpd.DataFrame)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> (dc_clean.shape == (6896, 10)) and (marvel_clean.shape == (16376, 10))\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> import numbers\n>>> isinstance(dc_clean.get("APPEARANCES").iloc[100], numbers.Integral)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> import numbers\n>>> isinstance(dc_clean.get("YEAR").iloc[100], numbers.Integral)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> import numbers\n>>> isinstance(marvel_clean.get("APPEARANCES").iloc[100], numbers.Integral)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> import numbers\n>>> isinstance(marvel_clean.get("YEAR").iloc[100], numbers.Integral)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
