test = {   'name': 'q7_4',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': ">>> callable(conditional_probability) and 0 < conditional_probability(['COMPANY', 'DC'], ['ALIGN', 'Good Characters']) < 1\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> np.isclose(conditional_probability(['COMPANY', 'DC'], ['ALIGN', 'Good Characters']), p_dc_given_good)\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
